- alias: Washing machine start
  id: Washing machine start
  initial_state: true
  trigger:
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: sensor.yandex_socket_current
  condition:
  - condition: numeric_state
    entity_id: sensor.yandex_socket_current
    above: '100'
  - condition: state
    entity_id: binary_sensor.washing_machine_door_contact
    state: 'off'
  - condition: state
    entity_id: input_boolean.washing_status
    state: 'off'
  - condition: state
    entity_id: input_boolean.washing_ends
    state: 'off'
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.washing_status

- alias: Washing machine end
  id: Washing machine end
  initial_state: true
  trigger:
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: sensor.yandex_socket_current
  condition:
  - condition: numeric_state
    entity_id: sensor.yandex_socket_current
    below: '20'
  - condition: state
    entity_id: binary_sensor.washing_machine_door_contact
    state: 'off'
  - condition: state
    entity_id: input_boolean.washing_status
    state: 'on'
  action:
  - delay:
      minutes: 1
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.washing_status
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.washing_ends
  - repeat:
      until:
      - condition: or
        conditions:
        - condition: state
          state: 'off'
          entity_id: input_boolean.washing_ends
        - condition: state
          entity_id: binary_sensor.washing_machine_door_contact
          state: 'on'
        - condition: state
          entity_id: input_boolean.washing_restart
          state: 'on'
      sequence:
      - service: notify.telegram
        data:
          message: 🧺Стирка закончилась, пора просушить белье
      - delay:
          hours: 0
          minutes: 30
          seconds: 0
          milliseconds: 0

- alias: Washing machine turn off
  id: Washing machine turn off
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.washing_machine_door_contact
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.washing_ends
    state: 'on'
  action:
  - service: input_boolean.turn_off
    target:
      entity_id:
      - input_boolean.washing_status
      - input_boolean.washing_restart
      - input_boolean.washing_ends

- alias: Washing machine restart
  id: Washing machine restart
  initial_state: true
  trigger:
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: sensor.yandex_socket_current
  condition:
  - condition: numeric_state
    entity_id: sensor.yandex_socket_current
    above: '100'
  - condition: state
    entity_id: input_boolean.washing_ends
    state: 'on'
  - condition: state
    entity_id: binary_sensor.washing_machine_door_contact
    state: 'off'
  - condition: state
    entity_id: input_boolean.washing_restart
    state: 'off'
  action:
  - service: input_boolean.turn_on
    target:
      entity_id:
      - input_boolean.washing_restart
      - input_boolean.washing_status

